// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoVuCAxpiszF5BC1SPRnNaHL75bBChzS0',
    appId: '1:443321100946:web:2610aab2cf3222794a144b',
    messagingSenderId: '443321100946',
    projectId: 'firewebviewdemo',
    authDomain: 'firewebviewdemo.firebaseapp.com',
    storageBucket: 'firewebviewdemo.appspot.com',
    measurementId: 'G-42QN1RMRVD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFw6e3YshsKV1XW5P-YkOGm8sCnZaXknM',
    appId: '1:443321100946:android:f1731f9865983d7f4a144b',
    messagingSenderId: '443321100946',
    projectId: 'firewebviewdemo',
    storageBucket: 'firewebviewdemo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5vY1WZJzpJYw7lTStDhlr2HLx7Esb-GE',
    appId: '1:443321100946:ios:c7bedbc5fb88afe74a144b',
    messagingSenderId: '443321100946',
    projectId: 'firewebviewdemo',
    storageBucket: 'firewebviewdemo.appspot.com',
    iosClientId: '443321100946-ij6u1jat8uka2lbpod5mpcf1519gn5ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.webviewdemo',
  );
}
